name: Simple Workflow

on: [push]

jobs:
  first_job:
    runs-on: ubuntu-latest

    outputs:
      example_output: ${{ steps.step1.outputs.example_output }}

    steps:
    - name: Generate output
      id: step1
      run: echo "example_output=Hello from the first job!" >> $GITHUB_ENV
    - name: Set output (compatibility step)
      id: step2
      run: echo "::set-output name=example_output::Hello from the first job!"

  second_job:
    runs-on: ubuntu-latest
    needs: first_job

    steps:
    - name: Use output from the first job
      run: echo "Output from first job: ${{ needs.first_job.outputs.example_output }}"
